version: "3.0"

services:
    postgres:
        container_name: postgres
        image: postgres:14
        env_file:
            - .env
        environment:
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
    main:
        container_name: user-api
        build:
            context: .
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 5000:5000
            - 9229:9229
        command: >
            sh -c "npm run build && npm start"
        depends_on:
            - postgres
        restart: always

volumes:
    pgdata:
